CREATE ROLE PG_USER_NAME WITH LOGIN PASSWORD 'PG_USER_PASSWORD';
CREATE ROLE PG_REPLICATION_NAME WITH LOGIN REPLICATION PASSWORD 'PG_REPLICATION_PASSWORD';
CREATE ROLE barman WITH SUPERUSER LOGIN REPLICATION PASSWORD 'PG_REPLICATION_PASSWORD';

CREATE DATABASE PG_DATABASE WITH OWNER PG_USER_NAME TEMPLATE template0 ENCODING PG_DATABASE_ENCODING;

\c PG_DATABASE
CREATE EXTENSION pg_stat_statements;
